name: dicom2stl

channels:
  - simpleitk
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - simpleitk
  - numpy
  - pip
  - pip:
    - pydicom
    - vtk
    - git+https://github.com/SimpleITK/SimpleITKUtilities.git@main
